using System.Text;
using App.Services.Oracle;
using Humanizer;

namespace App.Services.Exporters;

public class CSharpExportService : ICSharpExportService
{
    private readonly ITextExportService _textExportService;

    public CSharpExportService(ITextExportService textExportService)
    {
        _textExportService = textExportService ?? throw new ArgumentNullException(nameof(textExportService));
    }

    public async Task ExportOracleArgumentsAsync(ICollection<OracleArgument> oracleArguments, OracleArgs args, CancellationToken cancellationToken)
    {
        var name = GetCSharpName(args);
        var type = GetCSharpType(args);

        var csharpBuilder = new StringBuilder
        (
            $$"""
            // code generated by oracle-cli at {{DateTime.Now:F}}

            [OracleProperty("{{name}}")]
            public class {{type}}
            {
                {{GetCSharpArguments(oracleArguments)}}                
            }

            """
        );

        csharpBuilder.AppendLine($"{GetCSharpCursorClasses(oracleArguments)}");

        csharpBuilder.AppendLine
        (
            """
            public class OraclePropertyAttribute : Attribute
            {
                public string Name { get; }

                public OraclePropertyAttribute(string name)
                {
                    Name = name;
                }
            }
            """
        );

        var csharpText = csharpBuilder.ToString();
        await _textExportService.ExportToClipboardAsync(csharpText, cancellationToken);
    }
    
    private static string GetCSharpCursorClasses(IEnumerable<OracleArgument> oracleArguments)
    {
        var csharpBuilder = new StringBuilder();
        
        foreach (var oracleArgument in oracleArguments.Where(x => x.IsCursorType))
        {
            var cursorClassType = GetCSharpArgumentCursorType(oracleArgument);
            csharpBuilder.AppendLine();
            csharpBuilder.AppendLine
            (
                $$"""
                public class {{cursorClassType}}
                {
                    // cursor properties generation is not supported currently by oracle-cli
                }
                """
            );
        }

        return csharpBuilder.ToString();
    }

    private static string GetCSharpArguments(IEnumerable<OracleArgument> oracleArguments)
    {
        var csharpBuilder = new StringBuilder();
        
        foreach (var oracleArgument in oracleArguments)
        {
            var name = GetCSharpArgumentName(oracleArgument);
            var type = GetCSharpArgumentType(oracleArgument);
            csharpBuilder.AppendLine();
            csharpBuilder.AppendLine
            (
                $$"""
                    [OracleProperty("{{oracleArgument.Name}}")]
                    public {{type}} {{name}} { get; set; }
                """
            );
        }

        return csharpBuilder.ToString();
    }

    private static string GetCSharpArgumentName(OracleArgument oracleArgument)
    {
        var name = string.IsNullOrWhiteSpace(oracleArgument.Name)
            ? $"{oracleArgument.Direction}{oracleArgument.Position}"
            : oracleArgument.Name;
        
        return name.Transform(To.LowerCase).Pascalize();
    }

    private static string GetCSharpArgumentType(OracleArgument oracleArgument)
    {
        return oracleArgument.DataType.ToUpper() switch
        {
            "NUMBER" => "long",
            "VARCHAR" => "string",
            "VARCHAR2" => "string",
            "DATE" => "DateTime",
            "REF CURSOR" => GetCSharpArgumentCursorType(oracleArgument),
            _ => "NotSupportedType"
        };
    }

    private static string GetCSharpArgumentCursorType(OracleArgument oracleArgument)
    {
        return $"IEnumerable<OracleCursor{oracleArgument.Position}>";
    }

    private static string GetCSharpName(OracleArgs args)
    {
        var schemaName = args.OwnerName.ToUpper();
        var pkgName = args.PackageName?.ToUpper();
        var spcName = args.ProcedureName?.ToUpper();
        var funName = args.FunctionName?.ToUpper();
        var prgName = spcName ?? funName;
        return string.IsNullOrWhiteSpace(pkgName) 
            ? $"{schemaName}.{prgName}" 
            : $"{schemaName}.{pkgName}.{prgName}";
    }
    
    private static string GetCSharpType(OracleArgs args)
    {
        return string.IsNullOrWhiteSpace(args.FunctionName)
            ? "OracleProcedure"
            : "OracleFunction";
    }
}