using System.Text;
using System.Text.RegularExpressions;
using App.Services.Oracle;

namespace App.Services.Exporters;

public class SqlExporter : ISqlExporter
{
    public string ExportOracleSources(ICollection<OracleSource> oracleSources, OracleParameters parameters)
    {
        var sqlBuilder = new StringBuilder
        (
            $$"""
            // code generated by oracle-cli at {{DateTime.Now:F}}


            """
        );

        foreach (var oracleSource in oracleSources.Where(x => !string.IsNullOrWhiteSpace(x.Text)))
        {
            sqlBuilder.Append(oracleSource.Text);
        }

        return sqlBuilder.ToString();
    }

    public string ExportOracleSourcesErrors(ICollection<OracleSource> oracleSources, OracleParameters parameters)
    {
        if (!File.Exists(parameters.OutputFile))
        {
            return string.Empty;
        }

        var timeout = TimeSpan.FromSeconds(5);
        const RegexOptions options = RegexOptions.Compiled;
        var sql = File.ReadAllText(parameters.OutputFile);
        var errors = Regex.Matches(sql, @"(=>)(\s)('\w+')", options, timeout)
            .Select(CleanMatch)
            .Distinct()
            .ToList();
        return string.Join("\n", errors);
    }

    private static string CleanMatch(Match match)
    {
        return match.Value
            .Replace("=", "")
            .Replace(">", "")
            .Replace("'", "")
            .Trim();
    }
}